#!/bin/sh

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1

CSV_FILE="${CWD}/kr-en.csv"
if ! [ -f "$CSV_FILE" ]; then
    echo "No CSV file: $CSV_FILE" >&2
    exit 1
fi

CONVERTER="${CWD}/bin/csv-to-json"
if ! [ -x "$CONVERTER" ]; then
    echo "No CSV converter: $CONVERTER" >&2
    exit 1
fi

"$CONVERTER" "$CSV_FILE"