#!/usr/bin/env perl

use v5.36;

use FindBin;
use local::lib "$FindBin::Bin/../local";

use utf8;
use open ':std', ':encoding(UTF-8)';

use Cwd qw(getcwd);
use File::Spec::Functions;
use List::Util qw(shuffle);

use JSON;


use constant {
    PROGRAM => 'jp-dict-quiz',
    VERSION => '0.1.0'
};

my $pos;
my $mode = 'en2jp';
for my $arg (@ARGV) {
    if ($arg eq '-v' or $arg eq '--version') {
        print_version();
        exit(0);
    }
    elsif ($arg eq '-h' or $arg eq '--help') {
        print_help(*STDOUT);
        exit(0);
    }
    elsif (substr($arg, 0, length('-')) eq '-') {
        say {*STDERR} 'Unknown command-line argument: ' . $arg;
        say "";
        print_help(*STDERR);
        exit(1);
    }
    elsif ($arg eq 'en2jp' or $arg eq 'jp2en') {
        $mode = $arg;
        next;
    }

    $pos = $arg;
    last;
}

my $cwd = getcwd();
my $json_file = catfile($cwd, 'dist', 'dict.json');
(-e $json_file) or die "No dict file: ${json_file}\n";

open my $FH, "<:encoding(utf-8)", $json_file or die "Unable to open dict file: ${json_file}\n";
my $json_content = do { local $/; <$FH> };
close $FH;

my $json = JSON->new->canonical(0)->decode($json_content);

for my $lexicon (shuffle @{$json}) {
    next if ($pos and $lexicon->{'pos'} ne $pos);

    if ($mode eq 'en2jp') {
        say $lexicon->{'trans'};
    }
    else {
        if ($lexicon->{'kanji'}) {
            say $lexicon->{'kanji'};
        }
        else {
            say $lexicon->{'kana'};
        }
    }

    print 'Press Enter to show answer';
    readline(*STDIN);

    if ($mode eq 'en2jp') {
        print $lexicon->{'kana'} . " ";
        print $lexicon->{'kanji'} . " " if ($lexicon->{'kanji'});
        print $lexicon->{'loanword'} . " " if ($lexicon->{'loanword'});
        print $lexicon->{'pos'} . "\n";
    }
    else {
        say $lexicon->{'kana'} if ($lexicon->{'kanji'});
        say $lexicon->{'trans'};
    }

    say "";
}

sub print_version() {
    say VERSION;
}

sub print_help($stream) {
    print $stream <<~EOF_HELP
Usage: ${\PROGRAM} [option/pos]

Option:
    -v    --version    Show version info
    -h    --help       Show help info
    [pos]              Filter with Part of Speech
EOF_HELP
}